// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSWs7bGW6gwtam4qIerbiIxp6VRHxFhVQ',
    appId: '1:637719028278:web:bc7aef8a54180552cc2e97',
    messagingSenderId: '637719028278',
    projectId: 'ealanat-baladna',
    authDomain: 'ealanat-baladna.firebaseapp.com',
    storageBucket: 'ealanat-baladna.appspot.com',
    measurementId: 'G-NKJQ066FW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPHdIAk_HlrGT99xx0LsxqNMCUbBtqlg0',
    appId: '1:637719028278:android:a86cc7b6efccbce4cc2e97',
    messagingSenderId: '637719028278',
    projectId: 'ealanat-baladna',
    storageBucket: 'ealanat-baladna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9uZpy1JsFUO2WsMH2xAn_IIqEG2DWE4s',
    appId: '1:637719028278:ios:881324c046d35e8bcc2e97',
    messagingSenderId: '637719028278',
    projectId: 'ealanat-baladna',
    storageBucket: 'ealanat-baladna.appspot.com',
    iosBundleId: 'com.example.ealanatBaladna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9uZpy1JsFUO2WsMH2xAn_IIqEG2DWE4s',
    appId: '1:637719028278:ios:881324c046d35e8bcc2e97',
    messagingSenderId: '637719028278',
    projectId: 'ealanat-baladna',
    storageBucket: 'ealanat-baladna.appspot.com',
    iosBundleId: 'com.example.ealanatBaladna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSWs7bGW6gwtam4qIerbiIxp6VRHxFhVQ',
    appId: '1:637719028278:web:4a7637644c8e4feacc2e97',
    messagingSenderId: '637719028278',
    projectId: 'ealanat-baladna',
    authDomain: 'ealanat-baladna.firebaseapp.com',
    storageBucket: 'ealanat-baladna.appspot.com',
    measurementId: 'G-97KPTXXZQE',
  );
}
